POST http://localhost:8080/orders
Content-Type: application/json

{
  "orderNo": "SF-1234",
  "orderDate": "2020-12-17",
  "lines": [
    {
      "name": "T-shirt",
      "quantity": 5,
      "price": 15000
    },
    {
      "name": "Socks",
      "quantity": 3,
      "price": 900
    }
  ]
}